version: '3.3'
services:
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'lamp_db'
      MYSQL_USER: 'lamp_user'
      MYSQL_PASSWORD: '89423reufabvjkwsagiuolr'
      MYSQL_ROOT_PASSWORD: 'vfASDf433dajhgbfieruwep23edefgregvFGfj'
    volumes:
      - /home/ubuntu/pl_show/02_lamp_sh/data/mysql8:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - lamp

  mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    volumes:
      - /home/ubuntu/pl_show/02_lamp_sh/data/mssql2019:/var/opt/mssql
    ports:
      - "22433:1433"
    networks:
      - lamp



  httpd:
    image: httpd:pl-run
    volumes:
      - /home/ubuntu/pl_show/02_lamp_sh/data/lamp:/src/public
    depends_on:
      - php
      - mysqldb
      - mssqldb
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.lamp-http.rule=Host(`lamp-stack.test.local`)
        - traefik.http.routers.lamp-http.entrypoints=http
        - traefik.http.routers.lamp-http.middlewares=https-redirect
        - traefik.http.routers.lamp-https.rule=Host(`lamp-stack.test.local`)
        - traefik.http.routers.lamp-https.entrypoints=https
        - traefik.http.routers.lamp-https.tls=true
        - traefik.http.routers.lamp-https.tls.certresolver=le
        - traefik.http.services.lamp_httpd.loadbalancer.server.port=80
    ports:
      - '4488:80'
    networks:
      - lamp
      - traefik-public

  php:
    image: php:pl-run
    volumes:
      - /home/ubuntu/pl_show/02_lamp_sh/data/lamp/:/src/public
    depends_on:
      - mysqldb
      - mssqldb
    deploy:
      replicas: 3
    networks:
      - lamp

networks:
  lamp:
    driver: overlay
  traefik-public:
    external: true
